main: me.scatmancs.Lyra.Lyra
author: ScatmanCS
name: Lyra

commands:
  ores:
  setslots:
  ping:
  report:
  crate:
  list:
  staffmode:
    aliases: [staff, mod, h]
  vanish:
    aliases: [v]    